/* The question pool for "En Yakın" — guess a number, closest one wins.
 *
 * This file deliberately lives OUTSIDE public/. Only `public/` is served, so
 * the answers never reach a browser; the server deals a round and sends the
 * question text alone, and the number stays here until both people have
 * guessed. Putting these in public/games.js with the rest of the game would
 * have handed every answer to anyone who opened devtools.
 *
 * Every answer is a round, widely-cited figure, not a precise measurement —
 * this is a game about who is closer, not who is exact, and the card says so.
 */
export const QUESTIONS = [
  { tr: 'Türkiye’nin nüfusu kaç kişi?', en: 'What is the population of Türkiye?', a: 85400000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’de kaç il var?', en: 'How many provinces does Türkiye have?', a: 81, u: { tr: 'il', en: 'provinces' } },
  { tr: 'Türkiye’nin yüzölçümü kaç km²?', en: 'How large is Türkiye in km²?', a: 783562, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Türkiye’de trafiğe kayıtlı kaç motorlu taşıt var?', en: 'How many motor vehicles are registered in Türkiye?', a: 30000000, u: { tr: 'araç', en: 'vehicles' } },
  { tr: 'İstanbul’un nüfusu kaç kişi?', en: 'What is the population of Istanbul?', a: 15700000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’nin kıyı şeridi kaç km?', en: 'How long is Türkiye’s coastline?', a: 8333, u: { tr: 'km', en: 'km' } },
  { tr: 'Birleşmiş Milletler’in kaç üye ülkesi var?', en: 'How many member states does the UN have?', a: 193, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Dünya nüfusu kaç kişi?', en: 'What is the world’s population?', a: 8100000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Yetişkin bir insanda kaç kemik var?', en: 'How many bones are in an adult human?', a: 206, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Kalp günde ortalama kaç kez atar?', en: 'How many times does a heart beat in a day?', a: 100000, u: { tr: 'atış', en: 'beats' } },
  { tr: 'Bir insan günde ortalama kaç kez göz kırpar?', en: 'How many times a day does a person blink?', a: 17000, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir kafada ortalama kaç saç teli var?', en: 'How many hairs are on an average head?', a: 100000, u: { tr: 'tel', en: 'hairs' } },
  { tr: 'Ahtapotun kaç kalbi var?', en: 'How many hearts does an octopus have?', a: 3, u: { tr: 'kalp', en: 'hearts' } },
  { tr: 'Zürafanın boynunda kaç omur var?', en: 'How many neck bones does a giraffe have?', a: 7, u: { tr: 'omur', en: 'vertebrae' } },
  { tr: 'Ay ile Dünya arası ortalama kaç km?', en: 'How far is the Moon from Earth on average?', a: 384400, u: { tr: 'km', en: 'km' } },
  { tr: 'Güneş’in yüzey sıcaklığı kaç °C?', en: 'How hot is the Sun’s surface in °C?', a: 5500, u: { tr: '°C', en: '°C' } },
  { tr: 'Uzay İstasyonu saatte kaç km gider?', en: 'How fast does the Space Station travel per hour?', a: 27600, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Everest kaç metre?', en: 'How tall is Everest?', a: 8849, u: { tr: 'm', en: 'm' } },
  { tr: 'Okyanusun en derin noktası kaç metre?', en: 'How deep is the deepest point of the ocean?', a: 10935, u: { tr: 'm', en: 'm' } },
  { tr: 'Satrançta ilk hamlede kaç seçeneğin var?', en: 'How many first moves are there in chess?', a: 20, u: { tr: 'hamle', en: 'moves' } },
  { tr: 'Bir iskambil destesinde kaç kart var?', en: 'How many cards are in a deck?', a: 52, u: { tr: 'kart', en: 'cards' } },
  { tr: 'Bir piyanoda kaç tuş var?', en: 'How many keys does a piano have?', a: 88, u: { tr: 'tuş', en: 'keys' } },
  { tr: 'Olimpik yüzme havuzu kaç metre?', en: 'How long is an Olympic pool?', a: 50, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir maraton kaç km?', en: 'How long is a marathon?', a: 42, u: { tr: 'km', en: 'km' } },
  { tr: 'Ayasofya kaç yılında tamamlandı?', en: 'In what year was Hagia Sophia completed?', a: 537, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Bir arı 1 kg bal için kaç çiçeği ziyaret eder?', en: 'How many flowers do bees visit for 1 kg of honey?', a: 4000000, u: { tr: 'çiçek', en: 'flowers' } },
  { tr: 'Bir karınca kendi ağırlığının kaç katını taşır?', en: 'How many times its own weight can an ant carry?', a: 50, u: { tr: 'kat', en: 'times' } },
  { tr: 'Çita saatte kaç km koşar?', en: 'How fast can a cheetah run per hour?', a: 110, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Mavi balinanın dili kaç kg?', en: 'How much does a blue whale’s tongue weigh?', a: 2700, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir devekuşu yumurtası kaç gram?', en: 'How much does an ostrich egg weigh?', a: 1400, u: { tr: 'g', en: 'g' } },
  { tr: 'Bir yılda kaç saniye var?', en: 'How many seconds are in a year?', a: 31536000, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Bir günde kaç saniye var?', en: 'How many seconds are in a day?', a: 86400, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Dünyanın çevresi kaç km?', en: 'How far around is the Earth?', a: 40075, u: { tr: 'km', en: 'km' } },
  { tr: 'Işık saniyede kaç km yol alır?', en: 'How far does light travel in a second?', a: 300000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir muz kaç kalori?', en: 'How many calories are in a banana?', a: 105, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir fincan filtre kahvede kaç mg kafein var?', en: 'How much caffeine is in a cup of filter coffee?', a: 95, u: { tr: 'mg', en: 'mg' } },
  { tr: 'Dünyada günde kaç fincan kahve içiliyor?', en: 'How many cups of coffee are drunk daily worldwide?', a: 2000000000, u: { tr: 'fincan', en: 'cups' } },
  { tr: 'Bir bulut kaç ton ağırlığındadır?', en: 'How much does a cloud weigh?', a: 500, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Şimşek kaç °C’ye ulaşır?', en: 'How hot does a lightning bolt get?', a: 30000, u: { tr: '°C', en: '°C' } },
  { tr: 'Nil Nehri kaç km?', en: 'How long is the Nile?', a: 6650, u: { tr: 'km', en: 'km' } },
  { tr: 'Amazon Ormanı kaç km²?', en: 'How large is the Amazon rainforest?', a: 5500000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'En uzun sekoya ağacı kaç metre?', en: 'How tall is the tallest redwood?', a: 115, u: { tr: 'm', en: 'm' } },
  { tr: 'Bilinen en yaşlı ağaç kaç yaşında?', en: 'How old is the oldest known tree?', a: 4800, u: { tr: 'yıl', en: 'years' } },
  { tr: 'İnsan DNA’sında kaç baz çifti var?', en: 'How many base pairs are in human DNA?', a: 3200000000, u: { tr: 'baz çifti', en: 'base pairs' } },
  { tr: 'İnsan beyninde kaç nöron var?', en: 'How many neurons are in a human brain?', a: 86000000000, u: { tr: 'nöron', en: 'neurons' } },
  { tr: 'Ay’a kaç insan ayak bastı?', en: 'How many people have walked on the Moon?', a: 12, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Güneş sisteminde kaç gezegen var?', en: 'How many planets are in the solar system?', a: 8, u: { tr: 'gezegen', en: 'planets' } },
  { tr: 'Jüpiter’in bilinen kaç uydusu var?', en: 'How many known moons does Jupiter have?', a: 95, u: { tr: 'uydu', en: 'moons' } },
  { tr: 'Dünyada kaç dil konuşuluyor?', en: 'How many languages are spoken in the world?', a: 7000, u: { tr: 'dil', en: 'languages' } },
  { tr: 'Türk alfabesinde kaç harf var?', en: 'How many letters are in the Turkish alphabet?', a: 29, u: { tr: 'harf', en: 'letters' } },
  { tr: 'Bir insan ömrü boyunca kaç km yürür?', en: 'How far does a person walk in a lifetime?', a: 120000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir insan ömrünün kaç yılını uykuda geçirir?', en: 'How many years of a life are spent asleep?', a: 26, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir mum alevi kaç °C?', en: 'How hot is a candle flame?', a: 1000, u: { tr: '°C', en: '°C' } },
  { tr: 'İnsan vücudunda kaç litre kan var?', en: 'How many litres of blood are in a body?', a: 5, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Kan damarlarımızın toplam uzunluğu kaç km?', en: 'How long are all our blood vessels together?', a: 100000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir ayakta kaç kemik var?', en: 'How many bones are in one foot?', a: 26, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Bir elde kaç kemik var?', en: 'How many bones are in one hand?', a: 27, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Bir tavuk yılda kaç yumurta yumurtlar?', en: 'How many eggs does a hen lay in a year?', a: 300, u: { tr: 'yumurta', en: 'eggs' } },
  { tr: 'Bir inek günde kaç litre süt verir?', en: 'How much milk does a cow give per day?', a: 28, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir kovan yılda kaç kg bal yapar?', en: 'How much honey does a hive make in a year?', a: 25, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Türkiye yılda kaç ton fındık üretir?', en: 'How many tonnes of hazelnuts does Türkiye produce a year?', a: 700000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir çay bardağı kaç ml alır?', en: 'How many ml does a Turkish tea glass hold?', a: 100, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Aynı anda gökyüzünde kaç uçak olur?', en: 'How many planes are in the sky at once?', a: 10000, u: { tr: 'uçak', en: 'planes' } },
  { tr: 'İstanbul’dan New York’a kaç km?', en: 'How far is Istanbul from New York?', a: 8050, u: { tr: 'km', en: 'km' } },
  { tr: 'Dünyanın en uzun demiryolu tüneli kaç km?', en: 'How long is the world’s longest rail tunnel?', a: 57, u: { tr: 'km', en: 'km' } },
  { tr: 'Boğaziçi Köprüsü kaç metre?', en: 'How long is the Bosphorus Bridge?', a: 1560, u: { tr: 'm', en: 'm' } },
  { tr: 'Galata Kulesi kaç metre?', en: 'How tall is the Galata Tower?', a: 67, u: { tr: 'm', en: 'm' } },
  { tr: 'Çamlıca Kulesi kaç metre?', en: 'How tall is Çamlıca Tower?', a: 369, u: { tr: 'm', en: 'm' } },
  { tr: 'Kızılırmak kaç km?', en: 'How long is the Kızılırmak river?', a: 1355, u: { tr: 'km', en: 'km' } },
  { tr: 'Van Gölü kaç km²?', en: 'How large is Lake Van?', a: 3713, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Ağrı Dağı kaç metre?', en: 'How tall is Mount Ararat?', a: 5137, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir yılda kaç hafta var?', en: 'How many weeks are in a year?', a: 52, u: { tr: 'hafta', en: 'weeks' } },
  { tr: 'Dünyada yılda kaç ton çikolata tüketiliyor?', en: 'How much chocolate is eaten worldwide each year?', a: 7500000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: '1 kg bal için arılar toplam kaç km uçar?', en: 'How far do bees fly in total for 1 kg of honey?', a: 150000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir insanın vücudunda kaç kas var?', en: 'How many muscles are in a human body?', a: 600, u: { tr: 'kas', en: 'muscles' } },
  { tr: 'Bir yetişkinde kaç diş vardır?', en: 'How many teeth does an adult have?', a: 32, u: { tr: 'diş', en: 'teeth' } },
  { tr: 'Kelebeğin ömrü ortalama kaç gün?', en: 'How many days does a butterfly live?', a: 30, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir sinek saniyede kaç kez kanat çırpar?', en: 'How many times a second does a fly beat its wings?', a: 200, u: { tr: 'kez', en: 'times' } },
  { tr: 'Sinek kuşu saniyede kaç kez kanat çırpar?', en: 'How many times a second does a hummingbird beat its wings?', a: 55, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir fil günde kaç kg yiyecek yer?', en: 'How much does an elephant eat in a day?', a: 150, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir deve susuz kaç gün dayanabilir?', en: 'How many days can a camel go without water?', a: 15, u: { tr: 'gün', en: 'days' } },
  { tr: 'Kaplumbağa en fazla kaç yıl yaşar?', en: 'How long can a tortoise live?', a: 180, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir salyangoz saatte kaç metre gider?', en: 'How far does a snail travel in an hour?', a: 3, u: { tr: 'm', en: 'm' } },
  { tr: 'Penguen suda saatte kaç km yüzer?', en: 'How fast can a penguin swim per hour?', a: 10, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir yunusun beyni kaç gram?', en: 'How much does a dolphin’s brain weigh?', a: 1600, u: { tr: 'g', en: 'g' } },
  { tr: 'Dünyada kaç tür kuş var?', en: 'How many bird species are there?', a: 11000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Dünyada kaç tür karınca var?', en: 'How many ant species are there?', a: 14000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Bir metrekare toprakta kaç canlı yaşar?', en: 'How many creatures live in a square metre of soil?', a: 1000000000, u: { tr: 'canlı', en: 'creatures' } },
  { tr: 'Gökyüzünde çıplak gözle kaç yıldız görülür?', en: 'How many stars can be seen with the naked eye?', a: 5000, u: { tr: 'yıldız', en: 'stars' } },
  { tr: 'Samanyolu’nda kaç yıldız var?', en: 'How many stars are in the Milky Way?', a: 200000000000, u: { tr: 'yıldız', en: 'stars' } },
  { tr: 'Mars’a en yakın konumda kaç milyon km var?', en: 'How many million km away is Mars at its closest?', a: 55, u: { tr: 'milyon km', en: 'million km' } },
  { tr: 'Bir uzay giysisi kaç kg?', en: 'How much does a spacesuit weigh?', a: 130, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Dünya kendi ekseninde saatte kaç km döner?', en: 'How fast does Earth spin at the equator?', a: 1670, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir gökkuşağında kaç renk sayılır?', en: 'How many colours are counted in a rainbow?', a: 7, u: { tr: 'renk', en: 'colours' } },
  { tr: 'Bir kar tanesinin kaç kolu vardır?', en: 'How many arms does a snowflake have?', a: 6, u: { tr: 'kol', en: 'arms' } },
  { tr: 'Bir zeytin ağacı kaç yıl yaşayabilir?', en: 'How long can an olive tree live?', a: 1000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir bardak sütte kaç mg kalsiyum var?', en: 'How much calcium is in a glass of milk?', a: 300, u: { tr: 'mg', en: 'mg' } },
  { tr: 'Bir yumurta kaç kalori?', en: 'How many calories are in an egg?', a: 78, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir dilim ekmek kaç kalori?', en: 'How many calories are in a slice of bread?', a: 80, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'İnsan vücudunun yüzde kaçı sudur?', en: 'What percentage of the human body is water?', a: 60, u: { tr: '%', en: '%' } },
  { tr: 'Dünyanın yüzde kaçı okyanuslarla kaplı?', en: 'What percentage of Earth is covered by ocean?', a: 71, u: { tr: '%', en: '%' } },
  { tr: 'Bir futbol sahası kaç metre uzunluğunda?', en: 'How long is a football pitch?', a: 105, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir basketbol potası kaç cm yüksekliğinde?', en: 'How high is a basketball hoop?', a: 305, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Bir tenis topu kaç gram?', en: 'How much does a tennis ball weigh?', a: 58, u: { tr: 'g', en: 'g' } },
  { tr: 'Olimpiyatlar kaç yılda bir yapılır?', en: 'How often are the Olympics held?', a: 4, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir daktilo klavyesinde kaç tuş vardır?', en: 'How many keys does a keyboard have?', a: 104, u: { tr: 'tuş', en: 'keys' } },
  { tr: 'Wikipedia’da kaç İngilizce madde var?', en: 'How many English articles are on Wikipedia?', a: 6900000, u: { tr: 'madde', en: 'articles' } },
  { tr: 'Dünyada kaç akıllı telefon kullanıcısı var?', en: 'How many smartphone users are there?', a: 4900000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'YouTube’a dakikada kaç saatlik video yükleniyor?', en: 'How many hours of video are uploaded to YouTube per minute?', a: 500, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir A4 kağıdı pratikte kaç kez ikiye katlanabilir?', en: 'How many times can you fold an A4 sheet in half?', a: 7, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir kurşun kalemle kaç km çizgi çizilir?', en: 'How many km of line can one pencil draw?', a: 56, u: { tr: 'km', en: 'km' } },

  /* ---- Türkiye */
  { tr: 'Türkiye’de kaç ilçe var?', en: 'How many districts does Türkiye have?', a: 973, u: { tr: 'ilçe', en: 'districts' } },
  { tr: 'Ankara’nın nüfusu kaç kişi?', en: 'What is the population of Ankara?', a: 5800000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'İzmir’in nüfusu kaç kişi?', en: 'What is the population of Izmir?', a: 4500000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’de kaç üniversite var?', en: 'How many universities are there in Türkiye?', a: 208, u: { tr: 'üniversite', en: 'universities' } },
  { tr: 'Türkiye’yi yılda kaç turist ziyaret ediyor?', en: 'How many tourists visit Türkiye each year?', a: 50000000, u: { tr: 'turist', en: 'tourists' } },
  { tr: 'Türkiye’de kaç UNESCO Dünya Mirası alanı var?', en: 'How many UNESCO World Heritage sites are in Türkiye?', a: 21, u: { tr: 'alan', en: 'sites' } },
  { tr: 'Türkiye kaç ülkeyle kara sınırı paylaşıyor?', en: 'How many countries border Türkiye by land?', a: 8, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Fırat Nehri kaç km?', en: 'How long is the Euphrates?', a: 2800, u: { tr: 'km', en: 'km' } },
  { tr: 'Türkiye’de kaç havalimanı var?', en: 'How many airports does Türkiye have?', a: 57, u: { tr: 'havalimanı', en: 'airports' } },
  { tr: 'Uludağ kaç metre?', en: 'How tall is Mount Uludağ?', a: 2543, u: { tr: 'm', en: 'm' } },
  { tr: 'Erciyes Dağı kaç metre?', en: 'How tall is Mount Erciyes?', a: 3917, u: { tr: 'm', en: 'm' } },
  { tr: 'Tuz Gölü kaç km²?', en: 'How large is Lake Tuz?', a: 1665, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Anıtkabir kaç m² alana kurulu?', en: 'How large is the Anıtkabir site?', a: 750000, u: { tr: 'm²', en: 'm²' } },
  { tr: 'Topkapı Sarayı kaç m²?', en: 'How large is Topkapı Palace?', a: 700000, u: { tr: 'm²', en: 'm²' } },
  { tr: 'İstanbul Boğazı kaç km uzunluğunda?', en: 'How long is the Bosphorus?', a: 30, u: { tr: 'km', en: 'km' } },
  { tr: 'İstanbul Boğazı’nın en dar yeri kaç metre?', en: 'How narrow is the Bosphorus at its tightest?', a: 700, u: { tr: 'm', en: 'm' } },
  { tr: 'Çanakkale Boğazı kaç km?', en: 'How long is the Dardanelles?', a: 61, u: { tr: 'km', en: 'km' } },
  { tr: '1915 Çanakkale Köprüsü’nün orta açıklığı kaç metre?', en: 'How wide is the 1915 Çanakkale Bridge’s main span?', a: 2023, u: { tr: 'm', en: 'm' } },
  { tr: 'Marmara Denizi kaç km²?', en: 'How large is the Sea of Marmara?', a: 11350, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Türkiye yılda kaç ton kuru çay üretir?', en: 'How much dry tea does Türkiye produce a year?', a: 270000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Türkiye yılda kaç ton zeytin üretir?', en: 'How many tonnes of olives does Türkiye grow a year?', a: 1800000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Türkiye yılda kaç ton kayısı üretir?', en: 'How many tonnes of apricots does Türkiye grow a year?', a: 800000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Türkiye’de kaç cami var?', en: 'How many mosques are there in Türkiye?', a: 90000, u: { tr: 'cami', en: 'mosques' } },
  { tr: 'Göbeklitepe kaç yıllık?', en: 'How old is Göbekli Tepe?', a: 12000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Pamukkale travertenleri kaç metre yükseklikte?', en: 'How tall are the Pamukkale terraces?', a: 160, u: { tr: 'm', en: 'm' } },
  { tr: 'Türkiye’de kaç millî park var?', en: 'How many national parks does Türkiye have?', a: 49, u: { tr: 'park', en: 'parks' } },
  { tr: 'Türkiye’de kaç bitki türü yetişir?', en: 'How many plant species grow in Türkiye?', a: 12000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Türkiye’de kaç kuş türü görülür?', en: 'How many bird species are seen in Türkiye?', a: 500, u: { tr: 'tür', en: 'species' } },
  { tr: 'Bir Türk kahvesi fincanı kaç ml alır?', en: 'How much does a Turkish coffee cup hold?', a: 70, u: { tr: 'ml', en: 'ml' } },
  { tr: 'TDK Güncel Türkçe Sözlük’te kaç söz var?', en: 'How many entries are in the current Turkish dictionary?', a: 92000, u: { tr: 'söz', en: 'entries' } },
  { tr: 'Türkiye Cumhuriyeti kaç yılında kuruldu?', en: 'In what year was the Republic of Türkiye founded?', a: 1923, u: { tr: 'yıl', en: 'year' } },
  { tr: 'İstanbul kaç yılında fethedildi?', en: 'In what year was Istanbul conquered?', a: 1453, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Osmanlı İmparatorluğu kaç yıl sürdü?', en: 'How long did the Ottoman Empire last?', a: 623, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Türkiye’de kadınlar kaç yılında seçme hakkı kazandı?', en: 'In what year did women get the vote in Türkiye?', a: 1934, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Süleymaniye Camii kaç yılında tamamlandı?', en: 'In what year was the Süleymaniye Mosque finished?', a: 1557, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Türkiye’de kişi başına yılda kaç kg ekmek tüketiliyor?', en: 'How much bread does one person in Türkiye eat a year?', a: 100, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Sultanahmet Camii’nin kaç minaresi var?', en: 'How many minarets does the Blue Mosque have?', a: 6, u: { tr: 'minare', en: 'minarets' } },
  { tr: 'Ayasofya’nın kubbesi kaç metre çapında?', en: 'How wide is Hagia Sophia’s dome?', a: 31, u: { tr: 'm', en: 'm' } },
  { tr: 'Kapalıçarşı’da kaç dükkân var?', en: 'How many shops are in the Grand Bazaar?', a: 4000, u: { tr: 'dükkân', en: 'shops' } },
  { tr: 'Kapalıçarşı’yı günde kaç kişi geziyor?', en: 'How many people walk through the Grand Bazaar a day?', a: 300000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Nemrut Dağı’ndaki heykeller kaç metre?', en: 'How tall are the statues on Mount Nemrut?', a: 9, u: { tr: 'm', en: 'm' } },
  { tr: 'Efes Antik Tiyatrosu kaç kişilik?', en: 'How many people fit in the theatre at Ephesus?', a: 25000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Aspendos Tiyatrosu kaç kişilik?', en: 'How many people fit in the Aspendos theatre?', a: 15000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’de kaç termal kaynak var?', en: 'How many thermal springs are there in Türkiye?', a: 1500, u: { tr: 'kaynak', en: 'springs' } },
  { tr: 'Salda Gölü kaç metre derinlikte?', en: 'How deep is Lake Salda?', a: 196, u: { tr: 'm', en: 'm' } },
  { tr: 'Van Gölü kaç metre derinlikte?', en: 'How deep is Lake Van?', a: 451, u: { tr: 'm', en: 'm' } },
  { tr: 'Beyşehir Gölü kaç km²?', en: 'How large is Lake Beyşehir?', a: 650, u: { tr: 'km²', en: 'km²' } },
  { tr: 'İstanbul’da kaç metro istasyonu var?', en: 'How many metro stations does Istanbul have?', a: 140, u: { tr: 'istasyon', en: 'stations' } },
  { tr: 'Türkiye’nin en uzun tüneli kaç km?', en: 'How long is Türkiye’s longest tunnel?', a: 14, u: { tr: 'km', en: 'km' } },
  { tr: 'Türkiye’de kaç kütüphane var?', en: 'How many libraries are there in Türkiye?', a: 1200, u: { tr: 'kütüphane', en: 'libraries' } },

  /* ---- dünya coğrafyası */
  { tr: 'Dünyada kaç ülke var?', en: 'How many countries are there?', a: 195, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Rusya kaç km²?', en: 'How large is Russia?', a: 17100000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Çin’in nüfusu kaç kişi?', en: 'What is the population of China?', a: 1410000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Hindistan’ın nüfusu kaç kişi?', en: 'What is the population of India?', a: 1430000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'ABD’de kaç eyalet var?', en: 'How many states does the USA have?', a: 50, u: { tr: 'eyalet', en: 'states' } },
  { tr: 'Afrika’da kaç ülke var?', en: 'How many countries are in Africa?', a: 54, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Avrupa Birliği’nde kaç ülke var?', en: 'How many countries are in the EU?', a: 27, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Sahra Çölü kaç km²?', en: 'How large is the Sahara?', a: 9200000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Antarktika’daki buz ortalama kaç metre kalınlıkta?', en: 'How thick is Antarctic ice on average?', a: 2000, u: { tr: 'm', en: 'm' } },
  { tr: 'Amazon Nehri kaç km?', en: 'How long is the Amazon?', a: 6400, u: { tr: 'km', en: 'km' } },
  { tr: 'Mississippi Nehri kaç km?', en: 'How long is the Mississippi?', a: 3770, u: { tr: 'km', en: 'km' } },
  { tr: 'Baykal Gölü kaç metre derinlikte?', en: 'How deep is Lake Baikal?', a: 1642, u: { tr: 'm', en: 'm' } },
  { tr: 'Hazar Denizi kaç km²?', en: 'How large is the Caspian Sea?', a: 371000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Büyük Okyanus kaç km²?', en: 'How large is the Pacific Ocean?', a: 165000000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Vatikan kaç hektar?', en: 'How large is Vatican City?', a: 44, u: { tr: 'hektar', en: 'hectares' } },
  { tr: 'Tokyo bölgesinde kaç kişi yaşıyor?', en: 'How many people live in greater Tokyo?', a: 37000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Dünyada kaç şehirde 10 milyondan fazla insan yaşıyor?', en: 'How many cities have over 10 million people?', a: 33, u: { tr: 'şehir', en: 'cities' } },
  { tr: 'Burj Khalifa kaç metre?', en: 'How tall is the Burj Khalifa?', a: 828, u: { tr: 'm', en: 'm' } },
  { tr: 'Eyfel Kulesi kaç metre?', en: 'How tall is the Eiffel Tower?', a: 330, u: { tr: 'm', en: 'm' } },
  { tr: 'Özgürlük Anıtı kaç metre?', en: 'How tall is the Statue of Liberty?', a: 93, u: { tr: 'm', en: 'm' } },
  { tr: 'Çin Seddi kaç km?', en: 'How long is the Great Wall of China?', a: 21196, u: { tr: 'km', en: 'km' } },
  { tr: 'Büyük Piramit bugün kaç metre?', en: 'How tall is the Great Pyramid today?', a: 139, u: { tr: 'm', en: 'm' } },
  { tr: 'Kolezyum kaç kişilikti?', en: 'How many people did the Colosseum hold?', a: 50000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Machu Picchu kaç metre yükseklikte?', en: 'How high is Machu Picchu?', a: 2430, u: { tr: 'm', en: 'm' } },
  { tr: 'Niagara Şelalesi’nden saniyede kaç ton su akar?', en: 'How much water goes over Niagara Falls each second?', a: 2400, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Angel Şelalesi kaç metre?', en: 'How tall is Angel Falls?', a: 979, u: { tr: 'm', en: 'm' } },
  { tr: 'Ölü Deniz, deniz seviyesinden kaç metre aşağıda?', en: 'How far below sea level is the Dead Sea?', a: 430, u: { tr: 'm', en: 'm' } },
  { tr: 'Grand Canyon kaç km uzunluğunda?', en: 'How long is the Grand Canyon?', a: 446, u: { tr: 'km', en: 'km' } },
  { tr: 'Atacama Çölü’ne yılda kaç mm yağmur düşer?', en: 'How much rain falls on the Atacama in a year?', a: 15, u: { tr: 'mm', en: 'mm' } },
  { tr: 'Dünyada kaç aktif yanardağ var?', en: 'How many active volcanoes are there?', a: 1500, u: { tr: 'yanardağ', en: 'volcanoes' } },
  { tr: 'Dünyada yılda kaç deprem kaydediliyor?', en: 'How many earthquakes are recorded worldwide each year?', a: 500000, u: { tr: 'deprem', en: 'quakes' } },
  { tr: 'Dünyada kaç havalimanı var?', en: 'How many airports are there in the world?', a: 40000, u: { tr: 'havalimanı', en: 'airports' } },
  { tr: 'Endonezya’da kaç ada var?', en: 'How many islands does Indonesia have?', a: 17000, u: { tr: 'ada', en: 'islands' } },
  { tr: 'Dünyanın en uzun sınırı kaç km?', en: 'How long is the world’s longest border?', a: 8891, u: { tr: 'km', en: 'km' } },
  { tr: 'Dünyada kaç saat dilimi var?', en: 'How many time zones are there?', a: 38, u: { tr: 'dilim', en: 'zones' } },

  /* ---- hayvanlar ve doğa */
  { tr: 'Bir filin hamileliği kaç gün sürer?', en: 'How long is an elephant pregnant?', a: 645, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir kedi günde kaç saat uyur?', en: 'How many hours a day does a cat sleep?', a: 15, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir köpekte kaç koku alma hücresi var?', en: 'How many scent receptors does a dog have?', a: 300000000, u: { tr: 'hücre', en: 'receptors' } },
  { tr: 'Bir kedinin kaç bıyığı vardır?', en: 'How many whiskers does a cat have?', a: 24, u: { tr: 'bıyık', en: 'whiskers' } },
  { tr: 'Bir atın kalbi kaç kg?', en: 'How much does a horse’s heart weigh?', a: 4, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir zürafa günde kaç saat uyur?', en: 'How many hours a day does a giraffe sleep?', a: 2, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir koala günde kaç saat uyur?', en: 'How many hours a day does a koala sleep?', a: 20, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir yarasa saatte kaç sivrisinek yer?', en: 'How many mosquitoes can a bat eat in an hour?', a: 1000, u: { tr: 'sivrisinek', en: 'mosquitoes' } },
  { tr: 'Bir kovanda kaç arı yaşar?', en: 'How many bees live in one hive?', a: 50000, u: { tr: 'arı', en: 'bees' } },
  { tr: 'Bir kraliçe arı günde kaç yumurta bırakır?', en: 'How many eggs does a queen bee lay a day?', a: 2000, u: { tr: 'yumurta', en: 'eggs' } },
  { tr: 'Bir kartal avını kaç km öteden görür?', en: 'How far away can an eagle spot its prey?', a: 3, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir baykuşun başı kaç derece döner?', en: 'How far can an owl turn its head?', a: 270, u: { tr: 'derece', en: 'degrees' } },
  { tr: 'Bir timsahın ısırma gücü kaç kg?', en: 'How strong is a crocodile’s bite?', a: 1700, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir köpekbalığı ömrü boyunca kaç diş değiştirir?', en: 'How many teeth does a shark go through in its life?', a: 30000, u: { tr: 'diş', en: 'teeth' } },
  { tr: 'Bir denizanasının yüzde kaçı sudur?', en: 'What percentage of a jellyfish is water?', a: 95, u: { tr: '%', en: '%' } },
  { tr: 'Bir denizyıldızının kaç gözü var?', en: 'How many eyes does a starfish have?', a: 5, u: { tr: 'göz', en: 'eyes' } },
  { tr: 'Bir salyangozun kaç dişi var?', en: 'How many teeth does a snail have?', a: 14000, u: { tr: 'diş', en: 'teeth' } },
  { tr: 'Bir hamamböceği başsız kaç gün yaşar?', en: 'How long can a cockroach live without its head?', a: 7, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir tavşan yılda kaç yavru yapar?', en: 'How many young does a rabbit have in a year?', a: 30, u: { tr: 'yavru', en: 'young' } },
  { tr: 'Bir fare yılda kaç yavru doğurur?', en: 'How many young does a mouse have in a year?', a: 60, u: { tr: 'yavru', en: 'young' } },
  { tr: 'Bir kutup ayısı kaç kg?', en: 'How much does a polar bear weigh?', a: 450, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir kutup ayısı durmadan kaç km yüzebilir?', en: 'How far can a polar bear swim without stopping?', a: 100, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir penguen kaç metre dalabilir?', en: 'How deep can a penguin dive?', a: 500, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir mavi balina kaç ton?', en: 'How much does a blue whale weigh?', a: 150, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir mavi balinanın kalbi kaç kg?', en: 'How much does a blue whale’s heart weigh?', a: 180, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir balinanın sesi kaç km öteden duyulur?', en: 'How far away can a whale’s song be heard?', a: 800, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir yunus günde kaç km yüzer?', en: 'How far does a dolphin swim in a day?', a: 100, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir deniz kaplumbağası kaç yumurta bırakır?', en: 'How many eggs does a sea turtle lay?', a: 100, u: { tr: 'yumurta', en: 'eggs' } },
  { tr: 'Bir kirpide kaç diken var?', en: 'How many quills does a porcupine have?', a: 30000, u: { tr: 'diken', en: 'quills' } },
  { tr: 'Bir tavus kuşunun kuyruğunda kaç tüy var?', en: 'How many feathers are in a peacock’s tail?', a: 200, u: { tr: 'tüy', en: 'feathers' } },
  { tr: 'Bir devekuşu saatte kaç km koşar?', en: 'How fast can an ostrich run?', a: 70, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir doğan dalışta saatte kaç km yapar?', en: 'How fast does a falcon dive?', a: 320, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir kanguru tek seferde kaç metre zıplar?', en: 'How far can a kangaroo jump in one hop?', a: 9, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir tembel hayvan saatte kaç metre gider?', en: 'How far does a sloth travel in an hour?', a: 240, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir aslanın kükremesi kaç km öteden duyulur?', en: 'How far away can a lion’s roar be heard?', a: 8, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir su aygırı kaç kg?', en: 'How much does a hippo weigh?', a: 1500, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir gergedanın boynuzu kaç cm?', en: 'How long is a rhino’s horn?', a: 60, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Bir ağaç yılda kaç kg oksijen üretir?', en: 'How much oxygen does a tree make in a year?', a: 100, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir ağaç yılda kaç kg karbondioksit tutar?', en: 'How much CO₂ does a tree absorb in a year?', a: 22, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir ayçiçeği tablasında kaç çekirdek olur?', en: 'How many seeds are in one sunflower head?', a: 1500, u: { tr: 'çekirdek', en: 'seeds' } },
  { tr: 'Bir narda kaç tane olur?', en: 'How many seeds are in a pomegranate?', a: 600, u: { tr: 'tane', en: 'seeds' } },
  { tr: 'Bir kavakta yılda kaç yaprak açar?', en: 'How many leaves does a poplar grow in a year?', a: 200000, u: { tr: 'yaprak', en: 'leaves' } },

  /* ---- insan vücudu */
  { tr: 'Bir insan günde kaç kez nefes alır?', en: 'How many breaths does a person take a day?', a: 22000, u: { tr: 'nefes', en: 'breaths' } },
  { tr: 'Bir insan günde kaç litre hava soluk alır?', en: 'How much air does a person breathe in a day?', a: 11000, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir insan günde ortalama kaç kelime konuşur?', en: 'How many words does a person say in a day?', a: 16000, u: { tr: 'kelime', en: 'words' } },
  { tr: 'İnsan vücudunda kaç hücre var?', en: 'How many cells are in the human body?', a: 37000000000000, u: { tr: 'hücre', en: 'cells' } },
  { tr: 'Saç ayda kaç mm uzar?', en: 'How much does hair grow in a month?', a: 12, u: { tr: 'mm', en: 'mm' } },
  { tr: 'Tırnak ayda kaç mm uzar?', en: 'How much does a nail grow in a month?', a: 3, u: { tr: 'mm', en: 'mm' } },
  { tr: 'Deri kaç günde bir yenilenir?', en: 'How often does skin renew itself?', a: 28, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir insan günde kaç saç teli döker?', en: 'How many hairs does a person shed a day?', a: 100, u: { tr: 'tel', en: 'hairs' } },
  { tr: 'Bir hapşırık saatte kaç km hızla çıkar?', en: 'How fast does a sneeze travel?', a: 160, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir öksürük saatte kaç km hızla çıkar?', en: 'How fast does a cough travel?', a: 80, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Göz kaç farklı rengi ayırt edebilir?', en: 'How many colours can the eye tell apart?', a: 10000000, u: { tr: 'renk', en: 'colours' } },
  { tr: 'Kulak en fazla kaç Hz’e kadar duyar?', en: 'What is the highest frequency the ear can hear?', a: 20000, u: { tr: 'Hz', en: 'Hz' } },
  { tr: 'İnsan beyni kaç watt harcar?', en: 'How much power does the brain use?', a: 20, u: { tr: 'watt', en: 'watts' } },
  { tr: 'Beyin vücut ağırlığının yüzde kaçıdır?', en: 'What percentage of body weight is the brain?', a: 2, u: { tr: '%', en: '%' } },
  { tr: 'Bir insan beyni kaç gram?', en: 'How much does a human brain weigh?', a: 1400, u: { tr: 'g', en: 'g' } },
  { tr: 'Kan vücutta kaç saniyede bir tur atar?', en: 'How long does blood take to go round the body?', a: 60, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Bir kalp ömrü boyunca kaç kez atar?', en: 'How many times does a heart beat in a lifetime?', a: 2500000000, u: { tr: 'atış', en: 'beats' } },
  { tr: 'Bir insan ömrü boyunca kaç ton yiyecek yer?', en: 'How much food does a person eat in a lifetime?', a: 30, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir insan susuz kaç gün yaşayabilir?', en: 'How long can a person live without water?', a: 3, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir insan yemeden kaç gün yaşayabilir?', en: 'How long can a person live without food?', a: 30, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir gecede kaç rüya görülür?', en: 'How many dreams does a person have in one night?', a: 5, u: { tr: 'rüya', en: 'dreams' } },
  { tr: 'Bir gözde kaç ışık algılayıcı hücre var?', en: 'How many light-sensing cells are in one eye?', a: 130000000, u: { tr: 'hücre', en: 'cells' } },
  { tr: 'Dilde kaç tat tomurcuğu var?', en: 'How many taste buds are on the tongue?', a: 10000, u: { tr: 'tomurcuk', en: 'buds' } },
  { tr: 'Bir insan yılda kaç litre tükürük üretir?', en: 'How much saliva does a person make in a year?', a: 500, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir bebek kaç kemikle doğar?', en: 'How many bones is a baby born with?', a: 300, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'İskelet kaç yılda bir tamamen yenilenir?', en: 'How often does the skeleton fully renew?', a: 10, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir yetişkinin nabzı dakikada kaç atar?', en: 'What is a normal adult pulse per minute?', a: 72, u: { tr: 'atış', en: 'beats' } },
  { tr: 'Bir insanın bağırsakları kaç metre uzunluğunda?', en: 'How long are human intestines?', a: 8, u: { tr: 'm', en: 'm' } },
  { tr: 'Akciğerlerin toplam yüzeyi kaç m²?', en: 'How much surface area do the lungs have?', a: 70, u: { tr: 'm²', en: 'm²' } },
  { tr: 'Bir insanın derisi kaç kg?', en: 'How much does human skin weigh?', a: 4, u: { tr: 'kg', en: 'kg' } },

  /* ---- uzay */
  { tr: 'Güneş’in çapı kaç km?', en: 'How wide is the Sun?', a: 1392000, u: { tr: 'km', en: 'km' } },
  { tr: 'Dünya’nın çapı kaç km?', en: 'How wide is the Earth?', a: 12742, u: { tr: 'km', en: 'km' } },
  { tr: 'Ay’ın çapı kaç km?', en: 'How wide is the Moon?', a: 3474, u: { tr: 'km', en: 'km' } },
  { tr: 'Güneş kaç yaşında?', en: 'How old is the Sun?', a: 4600000000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Dünya kaç yaşında?', en: 'How old is the Earth?', a: 4540000000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Evren kaç yaşında?', en: 'How old is the universe?', a: 13800000000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Güneş ışığı Dünya’ya kaç dakikada gelir?', en: 'How long does sunlight take to reach Earth?', a: 8, u: { tr: 'dakika', en: 'minutes' } },
  { tr: 'Mars’ta bir gün kaç saat?', en: 'How long is a day on Mars?', a: 25, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Venüs’te bir gün kaç Dünya günü?', en: 'How long is a day on Venus in Earth days?', a: 243, u: { tr: 'gün', en: 'days' } },
  { tr: 'Jüpiter kendi ekseninde kaç saatte döner?', en: 'How long does Jupiter take to spin once?', a: 10, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Satürn’ün bilinen kaç uydusu var?', en: 'How many moons does Saturn have?', a: 146, u: { tr: 'uydu', en: 'moons' } },
  { tr: 'Plüton Güneş’in etrafında kaç yılda döner?', en: 'How long is a year on Pluto?', a: 248, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Uzay İstasyonu günde kaç kez Dünya’yı turlar?', en: 'How many times a day does the ISS circle Earth?', a: 16, u: { tr: 'tur', en: 'orbits' } },
  { tr: 'Uzay İstasyonu kaç metre uzunluğunda?', en: 'How long is the Space Station?', a: 109, u: { tr: 'm', en: 'm' } },
  { tr: 'Uzay İstasyonu kaç km yükseklikte uçar?', en: 'How high does the Space Station fly?', a: 400, u: { tr: 'km', en: 'km' } },
  { tr: 'Ay’a gitmek Apollo 11 için kaç gün sürdü?', en: 'How many days did Apollo 11 take to reach the Moon?', a: 3, u: { tr: 'gün', en: 'days' } },
  { tr: 'Apollo 11 kaç yılında Ay’a indi?', en: 'In what year did Apollo 11 land on the Moon?', a: 1969, u: { tr: 'yıl', en: 'year' } },
  { tr: 'İlk insan kaç yılında uzaya çıktı?', en: 'In what year did the first human go to space?', a: 1961, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Hubble teleskobu kaç yılında fırlatıldı?', en: 'In what year was Hubble launched?', a: 1990, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Voyager 1 Dünya’dan kaç milyar km uzakta?', en: 'How far from Earth is Voyager 1?', a: 24, u: { tr: 'milyar km', en: 'billion km' } },
  { tr: 'En yakın yıldız kaç ışık yılı uzakta?', en: 'How far away is the nearest star?', a: 4, u: { tr: 'ışık yılı', en: 'light years' } },
  { tr: 'Samanyolu kaç ışık yılı genişliğinde?', en: 'How wide is the Milky Way?', a: 100000, u: { tr: 'ışık yılı', en: 'light years' } },
  { tr: 'Evrende kaç galaksi var?', en: 'How many galaxies are in the universe?', a: 2000000000000, u: { tr: 'galaksi', en: 'galaxies' } },
  { tr: 'Dünya’ya günde kaç ton meteor tozu düşer?', en: 'How much meteor dust falls on Earth a day?', a: 100, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Yıldız kayması kaç km yükseklikte olur?', en: 'How high up does a shooting star burn?', a: 80, u: { tr: 'km', en: 'km' } },
  { tr: 'Ay, Dünya’dan yılda kaç cm uzaklaşır?', en: 'How far does the Moon drift away each year?', a: 4, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Dünya’nın yörüngesinde kaç çalışan uydu var?', en: 'How many working satellites orbit Earth?', a: 10000, u: { tr: 'uydu', en: 'satellites' } },
  { tr: 'Uzayda 10 cm’den büyük kaç çöp parçası dolaşıyor?', en: 'How many pieces of space junk over 10 cm are in orbit?', a: 36000, u: { tr: 'parça', en: 'pieces' } },
  { tr: 'Ay’ın yüzeyinde kaç krater var?', en: 'How many craters are on the Moon?', a: 300000, u: { tr: 'krater', en: 'craters' } },
  { tr: 'Bir astronot uzayda kaç cm uzar?', en: 'How much taller does an astronaut get in space?', a: 5, u: { tr: 'cm', en: 'cm' } },

  /* ---- yemek ve içecek */
  { tr: 'Bir dilim pizza kaç kalori?', en: 'How many calories are in a slice of pizza?', a: 285, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir hamburger kaç kalori?', en: 'How many calories are in a burger?', a: 550, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir baklava dilimi kaç kalori?', en: 'How many calories are in a piece of baklava?', a: 300, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir lahmacun kaç kalori?', en: 'How many calories are in a lahmacun?', a: 300, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir simit kaç kalori?', en: 'How many calories are in a simit?', a: 300, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir avokado kaç kalori?', en: 'How many calories are in an avocado?', a: 240, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir bardak portakal suyu kaç kalori?', en: 'How many calories are in a glass of orange juice?', a: 110, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir porsiyon pilav kaç kalori?', en: 'How many calories are in a portion of rice?', a: 250, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir kilo şekerde kaç kalori var?', en: 'How many calories are in a kilo of sugar?', a: 4000, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Dünyada yılda kaç ton kahve üretiliyor?', en: 'How much coffee is grown worldwide each year?', a: 10000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Dünyada yılda kaç ton pirinç üretiliyor?', en: 'How much rice is grown worldwide each year?', a: 520000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Dünyada yılda kaç ton muz yetişiyor?', en: 'How many bananas are grown worldwide each year?', a: 120000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Dünyada yılda kaç ton patates üretiliyor?', en: 'How many potatoes are grown worldwide each year?', a: 375000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Dünyada yılda kaç milyar yumurta üretiliyor?', en: 'How many eggs are produced worldwide each year?', a: 1600, u: { tr: 'milyar yumurta', en: 'billion eggs' } },
  { tr: 'Dünyada saniyede kaç şişe kola içiliyor?', en: 'How many Cokes are drunk worldwide each second?', a: 20000, u: { tr: 'şişe', en: 'bottles' } },
  { tr: 'Bir kilo kahve için kaç çekirdek gerekir?', en: 'How many beans go into a kilo of coffee?', a: 4000, u: { tr: 'çekirdek', en: 'beans' } },
  { tr: 'Bir şişe şarap kaç üzümden yapılır?', en: 'How many grapes go into one bottle of wine?', a: 600, u: { tr: 'üzüm', en: 'grapes' } },
  { tr: 'Bir kilo çilek kaç tane eder?', en: 'How many strawberries make a kilo?', a: 30, u: { tr: 'tane', en: 'berries' } },
  { tr: 'Bir hindistan cevizi kaç ml su içerir?', en: 'How much water is inside a coconut?', a: 250, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Bir limondan kaç ml su çıkar?', en: 'How much juice does one lemon give?', a: 45, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Dünyanın en acı biberi kaç Scoville?', en: 'How hot is the world’s hottest pepper?', a: 2600000, u: { tr: 'Scoville', en: 'Scoville' } },
  { tr: 'Bir çay kaşığı kaç ml?', en: 'How many ml is a teaspoon?', a: 5, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Bir yemek kaşığı kaç ml?', en: 'How many ml is a tablespoon?', a: 15, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Bir bardak suda kaç ml var?', en: 'How much water is in a glass?', a: 200, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Bir kilo bal kaç kalori?', en: 'How many calories are in a kilo of honey?', a: 3040, u: { tr: 'kalori', en: 'calories' } },

  /* ---- spor ve oyun */
  { tr: 'Bir NBA maçı kaç dakika sürer?', en: 'How long is an NBA game?', a: 48, u: { tr: 'dakika', en: 'minutes' } },
  { tr: 'Bir voleybol sahası kaç metre uzunluğunda?', en: 'How long is a volleyball court?', a: 18, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir tenis kortu kaç metre uzunluğunda?', en: 'How long is a tennis court?', a: 24, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir futbol kalesi kaç metre genişliğinde?', en: 'How wide is a football goal?', a: 7, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir futbol topu kaç gram?', en: 'How much does a football weigh?', a: 430, u: { tr: 'g', en: 'g' } },
  { tr: 'Bir basketbol topu kaç gram?', en: 'How much does a basketball weigh?', a: 620, u: { tr: 'g', en: 'g' } },
  { tr: 'Bir golf topunda kaç çukur var?', en: 'How many dimples are on a golf ball?', a: 336, u: { tr: 'çukur', en: 'dimples' } },
  { tr: 'Bir satranç tahtasında kaç kare var?', en: 'How many squares are on a chessboard?', a: 64, u: { tr: 'kare', en: 'squares' } },
  { tr: 'Bir tavla takımında kaç pul var?', en: 'How many pieces are in a backgammon set?', a: 30, u: { tr: 'pul', en: 'pieces' } },
  { tr: 'Bir domino setinde kaç taş var?', en: 'How many tiles are in a domino set?', a: 28, u: { tr: 'taş', en: 'tiles' } },
  { tr: 'Olimpiyatlarda kaç spor dalı var?', en: 'How many sports are in the Olympics?', a: 32, u: { tr: 'dal', en: 'sports' } },
  { tr: 'Dünya Kupası’na kaç takım katılır?', en: 'How many teams play in the World Cup?', a: 32, u: { tr: 'takım', en: 'teams' } },
  { tr: 'Bir maratonda kaç adım atılır?', en: 'How many steps are in a marathon?', a: 55000, u: { tr: 'adım', en: 'steps' } },
  { tr: 'Bir Formula 1 aracı saatte kaç km yapar?', en: 'How fast does a Formula 1 car go?', a: 350, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir Formula 1 pit stopu kaç saniye sürer?', en: 'How long does an F1 pit stop take?', a: 2, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Tour de France kaç km?', en: 'How long is the Tour de France?', a: 3500, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir maraton tam olarak kaç metre?', en: 'How many metres is a marathon exactly?', a: 42195, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir buz hokeyi diski kaç gram?', en: 'How much does a hockey puck weigh?', a: 170, u: { tr: 'g', en: 'g' } },
  { tr: 'Olimpik okçulukta hedef kaç metre uzakta?', en: 'How far is the Olympic archery target?', a: 70, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir dart tahtasında kaç dilim var?', en: 'How many segments are on a dartboard?', a: 20, u: { tr: 'dilim', en: 'segments' } },
  { tr: 'Bir bilardo masasında kaç top vardır?', en: 'How many balls are on a pool table?', a: 16, u: { tr: 'top', en: 'balls' } },
  { tr: 'Bir beyzbol topunda kaç dikiş var?', en: 'How many stitches are on a baseball?', a: 108, u: { tr: 'dikiş', en: 'stitches' } },
  { tr: '100 metre serbest yüzme rekoru kaç saniye?', en: 'What is the 100 m freestyle record in seconds?', a: 46, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Bir voleybol filesi kaç cm yükseklikte?', en: 'How high is a volleyball net?', a: 243, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Bir olimpik atletizm pisti kaç metre?', en: 'How long is an Olympic running track?', a: 400, u: { tr: 'm', en: 'm' } },

  /* ---- teknoloji */
  { tr: 'Dünyada kaç internet kullanıcısı var?', en: 'How many people use the internet?', a: 5400000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Google’da saniyede kaç arama yapılıyor?', en: 'How many Google searches happen each second?', a: 99000, u: { tr: 'arama', en: 'searches' } },
  { tr: 'Günde kaç milyar e-posta gönderiliyor?', en: 'How many emails are sent each day?', a: 350, u: { tr: 'milyar e-posta', en: 'billion emails' } },
  { tr: 'Dünyada günde kaç milyar fotoğraf çekiliyor?', en: 'How many photos are taken each day?', a: 5, u: { tr: 'milyar fotoğraf', en: 'billion photos' } },
  { tr: 'Instagram’a günde kaç fotoğraf yükleniyor?', en: 'How many photos go up on Instagram each day?', a: 95000000, u: { tr: 'fotoğraf', en: 'photos' } },
  { tr: 'WhatsApp’ta günde kaç milyar mesaj atılıyor?', en: 'How many WhatsApp messages are sent each day?', a: 100, u: { tr: 'milyar mesaj', en: 'billion messages' } },
  { tr: 'TikTok’un kaç kullanıcısı var?', en: 'How many people use TikTok?', a: 1600000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Dünyada kaç web sitesi var?', en: 'How many websites are there?', a: 1100000000, u: { tr: 'site', en: 'sites' } },
  { tr: 'İlk web sitesi kaç yılında yayına girdi?', en: 'In what year did the first website go online?', a: 1991, u: { tr: 'yıl', en: 'year' } },
  { tr: 'İlk iPhone kaç yılında çıktı?', en: 'In what year did the first iPhone come out?', a: 2007, u: { tr: 'yıl', en: 'year' } },
  { tr: 'İlk bilgisayar ENIAC kaç ton ağırlığındaydı?', en: 'How much did the ENIAC computer weigh?', a: 27, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir DVD kaç GB veri alır?', en: 'How much data fits on a DVD?', a: 5, u: { tr: 'GB', en: 'GB' } },
  { tr: 'Bir saatlik HD video kaç GB yer kaplar?', en: 'How much space does an hour of HD video take?', a: 3, u: { tr: 'GB', en: 'GB' } },
  { tr: 'Bir bitcoin kaç satoshi?', en: 'How many satoshi are in one bitcoin?', a: 100000000, u: { tr: 'satoshi', en: 'satoshi' } },
  { tr: 'Bitcoin kaç yılında ortaya çıktı?', en: 'In what year did Bitcoin appear?', a: 2009, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Dünyada kaç veri merkezi var?', en: 'How many data centres are there?', a: 11000, u: { tr: 'merkez', en: 'centres' } },
  { tr: 'Bir insan günde telefona kaç kez bakar?', en: 'How many times a day does a person check their phone?', a: 96, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir insan günde ekran başında kaç saat geçirir?', en: 'How many hours a day does a person spend on screens?', a: 7, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Netflix’te kaç film ve dizi var?', en: 'How many films and shows are on Netflix?', a: 6000, u: { tr: 'yapım', en: 'titles' } },
  { tr: 'Spotify’da kaç şarkı var?', en: 'How many songs are on Spotify?', a: 100000000, u: { tr: 'şarkı', en: 'songs' } },
  { tr: 'YouTube’da günde kaç saat video izleniyor?', en: 'How many hours of YouTube are watched each day?', a: 1000000000, u: { tr: 'saat', en: 'hours' } },
  { tr: 'İlk SMS kaç yılında gönderildi?', en: 'In what year was the first SMS sent?', a: 1992, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Wi-Fi kaç yılında kullanıma girdi?', en: 'In what year did Wi-Fi arrive?', a: 1997, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Bir GPS uydusu kaç km yükseklikte?', en: 'How high does a GPS satellite orbit?', a: 20200, u: { tr: 'km', en: 'km' } },
  { tr: 'Denizaltı internet kabloları toplam kaç km?', en: 'How many km of undersea internet cable are there?', a: 1400000, u: { tr: 'km', en: 'km' } },

  /* ---- tarih ve genel kültür */
  { tr: 'Amerika kaç yılında keşfedildi?', en: 'In what year was America reached by Columbus?', a: 1492, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Fransız İhtilali kaç yılında oldu?', en: 'In what year was the French Revolution?', a: 1789, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Birinci Dünya Savaşı kaç yılında başladı?', en: 'In what year did World War I start?', a: 1914, u: { tr: 'yıl', en: 'year' } },
  { tr: 'İkinci Dünya Savaşı kaç yıl sürdü?', en: 'How many years did World War II last?', a: 6, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Berlin Duvarı kaç yıl ayakta kaldı?', en: 'How long did the Berlin Wall stand?', a: 28, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Berlin Duvarı kaç km uzunluğundaydı?', en: 'How long was the Berlin Wall?', a: 155, u: { tr: 'km', en: 'km' } },
  { tr: 'Matbaa kaç yılında icat edildi?', en: 'In what year was the printing press invented?', a: 1440, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Titanic kaç yılında battı?', en: 'In what year did the Titanic sink?', a: 1912, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Titanic’te kaç kişi vardı?', en: 'How many people were on the Titanic?', a: 2224, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Mona Lisa kaç cm yüksekliğinde?', en: 'How tall is the Mona Lisa?', a: 77, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Louvre’da kaç eser var?', en: 'How many works does the Louvre hold?', a: 380000, u: { tr: 'eser', en: 'works' } },
  { tr: 'Louvre’u yılda kaç kişi ziyaret ediyor?', en: 'How many people visit the Louvre each year?', a: 8700000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Büyük Piramit’te kaç taş blok var?', en: 'How many stone blocks are in the Great Pyramid?', a: 2300000, u: { tr: 'blok', en: 'blocks' } },
  { tr: 'Sfenks kaç metre uzunluğunda?', en: 'How long is the Sphinx?', a: 73, u: { tr: 'm', en: 'm' } },
  { tr: 'Nobel Ödülü kaç yılından beri veriliyor?', en: 'Since what year has the Nobel Prize been awarded?', a: 1901, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Bugüne kadar kaç Nobel Ödülü verildi?', en: 'How many Nobel Prizes have been awarded so far?', a: 1000, u: { tr: 'ödül', en: 'prizes' } },
  { tr: 'Kaç dinozor türü keşfedildi?', en: 'How many dinosaur species have been found?', a: 1000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Dinozorlar kaç milyon yıl önce yok oldu?', en: 'How many million years ago did dinosaurs die out?', a: 66, u: { tr: 'milyon yıl', en: 'million years' } },
  { tr: 'Modern Olimpiyatlar kaç yılında başladı?', en: 'In what year did the modern Olympics begin?', a: 1896, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Dünyada kaç para birimi var?', en: 'How many currencies are there in the world?', a: 180, u: { tr: 'para birimi', en: 'currencies' } },
  { tr: 'İngilizceyi kaç kişi konuşuyor?', en: 'How many people speak English?', a: 1500000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Bir romanda ortalama kaç kelime vardır?', en: 'How many words are in an average novel?', a: 80000, u: { tr: 'kelime', en: 'words' } },
  { tr: 'Dünyada yılda kaç kitap yayımlanıyor?', en: 'How many books are published worldwide each year?', a: 2200000, u: { tr: 'kitap', en: 'books' } },
  { tr: 'Harry Potter kaç dile çevrildi?', en: 'Into how many languages has Harry Potter been translated?', a: 85, u: { tr: 'dil', en: 'languages' } },
  { tr: 'Dünyada kaç kütüphane var?', en: 'How many libraries are there in the world?', a: 2800000, u: { tr: 'kütüphane', en: 'libraries' } },

  /* ---- gündelik hayat */
  { tr: 'Bir otomobil lastiği kaç km gider?', en: 'How far does a car tyre last?', a: 50000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir uçak kalkarken saatte kaç km yapar?', en: 'How fast does a plane go at takeoff?', a: 280, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir yolcu uçağı kaç metre yükseklikte uçar?', en: 'How high does an airliner fly?', a: 11000, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir uçakta kaç parça bulunur?', en: 'How many parts does an airliner have?', a: 3000000, u: { tr: 'parça', en: 'parts' } },
  { tr: 'Bir asansör halatı kaç kg taşır?', en: 'How much can a lift cable hold?', a: 10000, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir ampul kaç saat yanar?', en: 'How many hours does a light bulb last?', a: 15000, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir çamaşır makinesi bir yıkamada kaç litre su harcar?', en: 'How much water does a wash use?', a: 50, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir duş dakikada kaç litre su akıtır?', en: 'How much water does a shower use per minute?', a: 10, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir insan günde kaç litre su içmeli?', en: 'How much water should a person drink a day?', a: 2, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir plastik şişe doğada kaç yılda çözünür?', en: 'How long does a plastic bottle take to break down?', a: 450, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir sakız doğada kaç yılda çözünür?', en: 'How long does chewing gum take to break down?', a: 5, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir cam şişe doğada kaç yılda çözünür?', en: 'How long does a glass bottle take to break down?', a: 4000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Dünyada yılda kaç ton plastik üretiliyor?', en: 'How much plastic is made worldwide each year?', a: 400000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Dünyada yılda kaç ton çöp çıkıyor?', en: 'How much rubbish does the world make each year?', a: 2000000000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir kağıt için kaç litre su harcanır?', en: 'How much water does one sheet of paper take?', a: 10, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir kot pantolon için kaç litre su harcanır?', en: 'How much water does a pair of jeans take?', a: 7500, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir insan ömrü boyunca kaç saat diş fırçalar?', en: 'How many hours does a person spend brushing their teeth?', a: 1100, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir insan ömrü boyunca kaç yıl çalışır?', en: 'How many years does a person spend working?', a: 10, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir insan hayatında kaç kişiyle tanışır?', en: 'How many people does a person meet in a lifetime?', a: 80000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Bir banknot kaç kez katlanınca yırtılır?', en: 'How many folds does a banknote take before it tears?', a: 4000, u: { tr: 'kez', en: 'folds' } },
  { tr: 'Bir madeni para kaç yıl dolaşımda kalır?', en: 'How long does a coin stay in circulation?', a: 30, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Dünyada günde kaç bebek doğuyor?', en: 'How many babies are born each day?', a: 385000, u: { tr: 'bebek', en: 'babies' } },
  { tr: 'Dünyada kaç çift ikiz doğuyor yılda?', en: 'How many pairs of twins are born each year?', a: 1600000, u: { tr: 'çift', en: 'pairs' } },
  { tr: 'Bir yıldırım kaç amper taşır?', en: 'How many amps does a lightning bolt carry?', a: 30000, u: { tr: 'amper', en: 'amps' } },
  { tr: 'Dünyada saniyede kaç şimşek çakar?', en: 'How many lightning strikes happen each second?', a: 100, u: { tr: 'şimşek', en: 'strikes' } },
  { tr: 'Bir kar fırtınasında saatte kaç cm kar yağar?', en: 'How much snow falls in an hour in a blizzard?', a: 5, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Bir hortum saatte kaç km hızla döner?', en: 'How fast does a tornado spin?', a: 300, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir yağmur damlası saatte kaç km düşer?', en: 'How fast does a raindrop fall?', a: 30, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir dolu tanesi en fazla kaç gram olur?', en: 'How heavy can a hailstone get?', a: 1000, u: { tr: 'g', en: 'g' } },
  { tr: 'Ses saniyede kaç metre yol alır?', en: 'How fast does sound travel?', a: 343, u: { tr: 'm', en: 'm' } },
];

export const QUESTION_COUNT = QUESTIONS.length;
