/* The question pool for "En Yakın" — guess a number, closest one wins.
 *
 * This file deliberately lives OUTSIDE public/. Only `public/` is served, so
 * the answers never reach a browser; the server deals a round and sends the
 * question text alone, and the number stays here until both people have
 * guessed. Putting these in public/games.js with the rest of the game would
 * have handed every answer to anyone who opened devtools.
 *
 * Every answer is a round, widely-cited figure, not a precise measurement —
 * this is a game about who is closer, not who is exact, and the card says so.
 */
export const QUESTIONS = [
  { tr: 'Türkiye’nin nüfusu kaç kişi?', en: 'What is the population of Türkiye?', a: 85400000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’de kaç il var?', en: 'How many provinces does Türkiye have?', a: 81, u: { tr: 'il', en: 'provinces' } },
  { tr: 'Türkiye’nin yüzölçümü kaç km²?', en: 'How large is Türkiye in km²?', a: 783562, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Türkiye’de trafiğe kayıtlı kaç motorlu taşıt var?', en: 'How many motor vehicles are registered in Türkiye?', a: 30000000, u: { tr: 'araç', en: 'vehicles' } },
  { tr: 'İstanbul’un nüfusu kaç kişi?', en: 'What is the population of Istanbul?', a: 15700000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Türkiye’nin kıyı şeridi kaç km?', en: 'How long is Türkiye’s coastline?', a: 8333, u: { tr: 'km', en: 'km' } },
  { tr: 'Birleşmiş Milletler’in kaç üye ülkesi var?', en: 'How many member states does the UN have?', a: 193, u: { tr: 'ülke', en: 'countries' } },
  { tr: 'Dünya nüfusu kaç kişi?', en: 'What is the world’s population?', a: 8100000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Yetişkin bir insanda kaç kemik var?', en: 'How many bones are in an adult human?', a: 206, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Kalp günde ortalama kaç kez atar?', en: 'How many times does a heart beat in a day?', a: 100000, u: { tr: 'atış', en: 'beats' } },
  { tr: 'Bir insan günde ortalama kaç kez göz kırpar?', en: 'How many times a day does a person blink?', a: 17000, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir kafada ortalama kaç saç teli var?', en: 'How many hairs are on an average head?', a: 100000, u: { tr: 'tel', en: 'hairs' } },
  { tr: 'Ahtapotun kaç kalbi var?', en: 'How many hearts does an octopus have?', a: 3, u: { tr: 'kalp', en: 'hearts' } },
  { tr: 'Zürafanın boynunda kaç omur var?', en: 'How many neck bones does a giraffe have?', a: 7, u: { tr: 'omur', en: 'vertebrae' } },
  { tr: 'Ay ile Dünya arası ortalama kaç km?', en: 'How far is the Moon from Earth on average?', a: 384400, u: { tr: 'km', en: 'km' } },
  { tr: 'Güneş’in yüzey sıcaklığı kaç °C?', en: 'How hot is the Sun’s surface in °C?', a: 5500, u: { tr: '°C', en: '°C' } },
  { tr: 'Uzay İstasyonu saatte kaç km gider?', en: 'How fast does the Space Station travel per hour?', a: 27600, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Everest kaç metre?', en: 'How tall is Everest?', a: 8849, u: { tr: 'm', en: 'm' } },
  { tr: 'Okyanusun en derin noktası kaç metre?', en: 'How deep is the deepest point of the ocean?', a: 10935, u: { tr: 'm', en: 'm' } },
  { tr: 'Satrançta ilk hamlede kaç seçeneğin var?', en: 'How many first moves are there in chess?', a: 20, u: { tr: 'hamle', en: 'moves' } },
  { tr: 'Bir iskambil destesinde kaç kart var?', en: 'How many cards are in a deck?', a: 52, u: { tr: 'kart', en: 'cards' } },
  { tr: 'Bir piyanoda kaç tuş var?', en: 'How many keys does a piano have?', a: 88, u: { tr: 'tuş', en: 'keys' } },
  { tr: 'Olimpik yüzme havuzu kaç metre?', en: 'How long is an Olympic pool?', a: 50, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir maraton kaç km?', en: 'How long is a marathon?', a: 42, u: { tr: 'km', en: 'km' } },
  { tr: 'Ayasofya kaç yılında tamamlandı?', en: 'In what year was Hagia Sophia completed?', a: 537, u: { tr: 'yıl', en: 'year' } },
  { tr: 'Bir arı 1 kg bal için kaç çiçeği ziyaret eder?', en: 'How many flowers do bees visit for 1 kg of honey?', a: 4000000, u: { tr: 'çiçek', en: 'flowers' } },
  { tr: 'Bir karınca kendi ağırlığının kaç katını taşır?', en: 'How many times its own weight can an ant carry?', a: 50, u: { tr: 'kat', en: 'times' } },
  { tr: 'Çita saatte kaç km koşar?', en: 'How fast can a cheetah run per hour?', a: 110, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Mavi balinanın dili kaç kg?', en: 'How much does a blue whale’s tongue weigh?', a: 2700, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir devekuşu yumurtası kaç gram?', en: 'How much does an ostrich egg weigh?', a: 1400, u: { tr: 'g', en: 'g' } },
  { tr: 'Bir yılda kaç saniye var?', en: 'How many seconds are in a year?', a: 31536000, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Bir günde kaç saniye var?', en: 'How many seconds are in a day?', a: 86400, u: { tr: 'saniye', en: 'seconds' } },
  { tr: 'Dünyanın çevresi kaç km?', en: 'How far around is the Earth?', a: 40075, u: { tr: 'km', en: 'km' } },
  { tr: 'Işık saniyede kaç km yol alır?', en: 'How far does light travel in a second?', a: 300000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir muz kaç kalori?', en: 'How many calories are in a banana?', a: 105, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir fincan filtre kahvede kaç mg kafein var?', en: 'How much caffeine is in a cup of filter coffee?', a: 95, u: { tr: 'mg', en: 'mg' } },
  { tr: 'Dünyada günde kaç fincan kahve içiliyor?', en: 'How many cups of coffee are drunk daily worldwide?', a: 2000000000, u: { tr: 'fincan', en: 'cups' } },
  { tr: 'Bir bulut kaç ton ağırlığındadır?', en: 'How much does a cloud weigh?', a: 500, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Şimşek kaç °C’ye ulaşır?', en: 'How hot does a lightning bolt get?', a: 30000, u: { tr: '°C', en: '°C' } },
  { tr: 'Nil Nehri kaç km?', en: 'How long is the Nile?', a: 6650, u: { tr: 'km', en: 'km' } },
  { tr: 'Amazon Ormanı kaç km²?', en: 'How large is the Amazon rainforest?', a: 5500000, u: { tr: 'km²', en: 'km²' } },
  { tr: 'En uzun sekoya ağacı kaç metre?', en: 'How tall is the tallest redwood?', a: 115, u: { tr: 'm', en: 'm' } },
  { tr: 'Bilinen en yaşlı ağaç kaç yaşında?', en: 'How old is the oldest known tree?', a: 4800, u: { tr: 'yıl', en: 'years' } },
  { tr: 'İnsan DNA’sında kaç baz çifti var?', en: 'How many base pairs are in human DNA?', a: 3200000000, u: { tr: 'baz çifti', en: 'base pairs' } },
  { tr: 'İnsan beyninde kaç nöron var?', en: 'How many neurons are in a human brain?', a: 86000000000, u: { tr: 'nöron', en: 'neurons' } },
  { tr: 'Ay’a kaç insan ayak bastı?', en: 'How many people have walked on the Moon?', a: 12, u: { tr: 'kişi', en: 'people' } },
  { tr: 'Güneş sisteminde kaç gezegen var?', en: 'How many planets are in the solar system?', a: 8, u: { tr: 'gezegen', en: 'planets' } },
  { tr: 'Jüpiter’in bilinen kaç uydusu var?', en: 'How many known moons does Jupiter have?', a: 95, u: { tr: 'uydu', en: 'moons' } },
  { tr: 'Dünyada kaç dil konuşuluyor?', en: 'How many languages are spoken in the world?', a: 7000, u: { tr: 'dil', en: 'languages' } },
  { tr: 'Türk alfabesinde kaç harf var?', en: 'How many letters are in the Turkish alphabet?', a: 29, u: { tr: 'harf', en: 'letters' } },
  { tr: 'Bir insan ömrü boyunca kaç km yürür?', en: 'How far does a person walk in a lifetime?', a: 120000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir insan ömrünün kaç yılını uykuda geçirir?', en: 'How many years of a life are spent asleep?', a: 26, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir mum alevi kaç °C?', en: 'How hot is a candle flame?', a: 1000, u: { tr: '°C', en: '°C' } },
  { tr: 'İnsan vücudunda kaç litre kan var?', en: 'How many litres of blood are in a body?', a: 5, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Kan damarlarımızın toplam uzunluğu kaç km?', en: 'How long are all our blood vessels together?', a: 100000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir ayakta kaç kemik var?', en: 'How many bones are in one foot?', a: 26, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Bir elde kaç kemik var?', en: 'How many bones are in one hand?', a: 27, u: { tr: 'kemik', en: 'bones' } },
  { tr: 'Bir tavuk yılda kaç yumurta yumurtlar?', en: 'How many eggs does a hen lay in a year?', a: 300, u: { tr: 'yumurta', en: 'eggs' } },
  { tr: 'Bir inek günde kaç litre süt verir?', en: 'How much milk does a cow give per day?', a: 28, u: { tr: 'litre', en: 'litres' } },
  { tr: 'Bir kovan yılda kaç kg bal yapar?', en: 'How much honey does a hive make in a year?', a: 25, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Türkiye yılda kaç ton fındık üretir?', en: 'How many tonnes of hazelnuts does Türkiye produce a year?', a: 700000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: 'Bir çay bardağı kaç ml alır?', en: 'How many ml does a Turkish tea glass hold?', a: 100, u: { tr: 'ml', en: 'ml' } },
  { tr: 'Aynı anda gökyüzünde kaç uçak olur?', en: 'How many planes are in the sky at once?', a: 10000, u: { tr: 'uçak', en: 'planes' } },
  { tr: 'İstanbul’dan New York’a kaç km?', en: 'How far is Istanbul from New York?', a: 8050, u: { tr: 'km', en: 'km' } },
  { tr: 'Dünyanın en uzun demiryolu tüneli kaç km?', en: 'How long is the world’s longest rail tunnel?', a: 57, u: { tr: 'km', en: 'km' } },
  { tr: 'Boğaziçi Köprüsü kaç metre?', en: 'How long is the Bosphorus Bridge?', a: 1560, u: { tr: 'm', en: 'm' } },
  { tr: 'Galata Kulesi kaç metre?', en: 'How tall is the Galata Tower?', a: 67, u: { tr: 'm', en: 'm' } },
  { tr: 'Çamlıca Kulesi kaç metre?', en: 'How tall is Çamlıca Tower?', a: 369, u: { tr: 'm', en: 'm' } },
  { tr: 'Kızılırmak kaç km?', en: 'How long is the Kızılırmak river?', a: 1355, u: { tr: 'km', en: 'km' } },
  { tr: 'Van Gölü kaç km²?', en: 'How large is Lake Van?', a: 3713, u: { tr: 'km²', en: 'km²' } },
  { tr: 'Ağrı Dağı kaç metre?', en: 'How tall is Mount Ararat?', a: 5137, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir yılda kaç hafta var?', en: 'How many weeks are in a year?', a: 52, u: { tr: 'hafta', en: 'weeks' } },
  { tr: 'Dünyada yılda kaç ton çikolata tüketiliyor?', en: 'How much chocolate is eaten worldwide each year?', a: 7500000, u: { tr: 'ton', en: 'tonnes' } },
  { tr: '1 kg bal için arılar toplam kaç km uçar?', en: 'How far do bees fly in total for 1 kg of honey?', a: 150000, u: { tr: 'km', en: 'km' } },
  { tr: 'Bir insanın vücudunda kaç kas var?', en: 'How many muscles are in a human body?', a: 600, u: { tr: 'kas', en: 'muscles' } },
  { tr: 'Bir yetişkinde kaç diş vardır?', en: 'How many teeth does an adult have?', a: 32, u: { tr: 'diş', en: 'teeth' } },
  { tr: 'Kelebeğin ömrü ortalama kaç gün?', en: 'How many days does a butterfly live?', a: 30, u: { tr: 'gün', en: 'days' } },
  { tr: 'Bir sinek saniyede kaç kez kanat çırpar?', en: 'How many times a second does a fly beat its wings?', a: 200, u: { tr: 'kez', en: 'times' } },
  { tr: 'Sinek kuşu saniyede kaç kez kanat çırpar?', en: 'How many times a second does a hummingbird beat its wings?', a: 55, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir fil günde kaç kg yiyecek yer?', en: 'How much does an elephant eat in a day?', a: 150, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Bir deve susuz kaç gün dayanabilir?', en: 'How many days can a camel go without water?', a: 15, u: { tr: 'gün', en: 'days' } },
  { tr: 'Kaplumbağa en fazla kaç yıl yaşar?', en: 'How long can a tortoise live?', a: 180, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir salyangoz saatte kaç metre gider?', en: 'How far does a snail travel in an hour?', a: 3, u: { tr: 'm', en: 'm' } },
  { tr: 'Penguen suda saatte kaç km yüzer?', en: 'How fast can a penguin swim per hour?', a: 10, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir yunusun beyni kaç gram?', en: 'How much does a dolphin’s brain weigh?', a: 1600, u: { tr: 'g', en: 'g' } },
  { tr: 'Dünyada kaç tür kuş var?', en: 'How many bird species are there?', a: 11000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Dünyada kaç tür karınca var?', en: 'How many ant species are there?', a: 14000, u: { tr: 'tür', en: 'species' } },
  { tr: 'Bir metrekare toprakta kaç canlı yaşar?', en: 'How many creatures live in a square metre of soil?', a: 1000000000, u: { tr: 'canlı', en: 'creatures' } },
  { tr: 'Gökyüzünde çıplak gözle kaç yıldız görülür?', en: 'How many stars can be seen with the naked eye?', a: 5000, u: { tr: 'yıldız', en: 'stars' } },
  { tr: 'Samanyolu’nda kaç yıldız var?', en: 'How many stars are in the Milky Way?', a: 200000000000, u: { tr: 'yıldız', en: 'stars' } },
  { tr: 'Mars’a en yakın konumda kaç milyon km var?', en: 'How many million km away is Mars at its closest?', a: 55, u: { tr: 'milyon km', en: 'million km' } },
  { tr: 'Bir uzay giysisi kaç kg?', en: 'How much does a spacesuit weigh?', a: 130, u: { tr: 'kg', en: 'kg' } },
  { tr: 'Dünya kendi ekseninde saatte kaç km döner?', en: 'How fast does Earth spin at the equator?', a: 1670, u: { tr: 'km/sa', en: 'km/h' } },
  { tr: 'Bir gökkuşağında kaç renk sayılır?', en: 'How many colours are counted in a rainbow?', a: 7, u: { tr: 'renk', en: 'colours' } },
  { tr: 'Bir kar tanesinin kaç kolu vardır?', en: 'How many arms does a snowflake have?', a: 6, u: { tr: 'kol', en: 'arms' } },
  { tr: 'Bir zeytin ağacı kaç yıl yaşayabilir?', en: 'How long can an olive tree live?', a: 1000, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir bardak sütte kaç mg kalsiyum var?', en: 'How much calcium is in a glass of milk?', a: 300, u: { tr: 'mg', en: 'mg' } },
  { tr: 'Bir yumurta kaç kalori?', en: 'How many calories are in an egg?', a: 78, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'Bir dilim ekmek kaç kalori?', en: 'How many calories are in a slice of bread?', a: 80, u: { tr: 'kalori', en: 'calories' } },
  { tr: 'İnsan vücudunun yüzde kaçı sudur?', en: 'What percentage of the human body is water?', a: 60, u: { tr: '%', en: '%' } },
  { tr: 'Dünyanın yüzde kaçı okyanuslarla kaplı?', en: 'What percentage of Earth is covered by ocean?', a: 71, u: { tr: '%', en: '%' } },
  { tr: 'Bir futbol sahası kaç metre uzunluğunda?', en: 'How long is a football pitch?', a: 105, u: { tr: 'm', en: 'm' } },
  { tr: 'Bir basketbol potası kaç cm yüksekliğinde?', en: 'How high is a basketball hoop?', a: 305, u: { tr: 'cm', en: 'cm' } },
  { tr: 'Bir tenis topu kaç gram?', en: 'How much does a tennis ball weigh?', a: 58, u: { tr: 'g', en: 'g' } },
  { tr: 'Olimpiyatlar kaç yılda bir yapılır?', en: 'How often are the Olympics held?', a: 4, u: { tr: 'yıl', en: 'years' } },
  { tr: 'Bir daktilo klavyesinde kaç tuş vardır?', en: 'How many keys does a keyboard have?', a: 104, u: { tr: 'tuş', en: 'keys' } },
  { tr: 'Wikipedia’da kaç İngilizce madde var?', en: 'How many English articles are on Wikipedia?', a: 6900000, u: { tr: 'madde', en: 'articles' } },
  { tr: 'Dünyada kaç akıllı telefon kullanıcısı var?', en: 'How many smartphone users are there?', a: 4900000000, u: { tr: 'kişi', en: 'people' } },
  { tr: 'YouTube’a dakikada kaç saatlik video yükleniyor?', en: 'How many hours of video are uploaded to YouTube per minute?', a: 500, u: { tr: 'saat', en: 'hours' } },
  { tr: 'Bir A4 kağıdı pratikte kaç kez ikiye katlanabilir?', en: 'How many times can you fold an A4 sheet in half?', a: 7, u: { tr: 'kez', en: 'times' } },
  { tr: 'Bir kurşun kalemle kaç km çizgi çizilir?', en: 'How many km of line can one pencil draw?', a: 56, u: { tr: 'km', en: 'km' } },
];

export const QUESTION_COUNT = QUESTIONS.length;
