/* A common-word list for Word Chain's dictionary mode.
 *
 * Like questions.js this lives OUTSIDE public/, because the server is the one
 * that decides whether a word counts and there is no reason to ship the list
 * to a browser.
 *
 * It is deliberately a list of ordinary, everyday Turkish words rather than a
 * dictionary: a real one is enormous, and the point of the mode is to make
 * the chain harder in a way both people can predict. Anything outside it is
 * simply not accepted in dictionary mode — free mode takes any Turkish
 * letters, which is the default.
 */
export const WORDS = new Set([
  'ABLA', 'ADA', 'ADAM', 'ADRES', 'AHIR', 'AİLE', 'AKIL', 'AKŞAM',
  'ALAN', 'ALEV', 'ALTIN', 'ALIN', 'ANA', 'ANAHTAR', 'ANKARA', 'ANLAM',
  'ANNE', 'ARA', 'ARABA', 'ARKA', 'ARMUT', 'ARSA', 'ARI', 'ASKER',
  'ASLAN', 'AT', 'ATEŞ', 'ATKI', 'AV', 'AVLU', 'AY', 'AYAK',
  'AYNA', 'AYRAN', 'AYVA', 'AYI', 'AZ', 'AZIK', 'AĞAÇ', 'AĞIR',
  'AĞIZ', 'AŞK', 'BABA', 'BACAK', 'BAHAR', 'BAHÇE', 'BAKIR', 'BAL',
  'BALKON', 'BALON', 'BALIK', 'BANT', 'BARDAK', 'BARIŞ', 'BASAMAK', 'BATI',
  'BAVUL', 'BAY', 'BAYAN', 'BAYRAK', 'BAŞ', 'BAŞAK', 'BEBEK', 'BEDEN',
  'BEKÇİ', 'BELDE', 'BELGE', 'BEN', 'BENİZ', 'BERBER', 'BEREKET', 'BEYAZ',
  'BEYİN', 'BEZ', 'BİBER', 'BİLEK', 'BİLGİ', 'BİLİM', 'BİNA', 'BİNEK',
  'BİRA', 'BİRLİK', 'BİSİKLET', 'BİT', 'BİYOLOJİ', 'BİZ', 'BLUZ', 'BOBİN',
  'BONCUK', 'BORU', 'BOYA', 'BOYUN', 'BOZUK', 'BOĞA', 'BULUT', 'BURUN',
  'BUZ', 'BÖLGE', 'BÖREK', 'BÜCÜR', 'BÜLBÜL', 'BÜRO', 'BÜYÜ', 'CADDE',
  'CAM', 'CAN', 'CANAVAR', 'CEKET', 'CEP', 'CETVEL', 'CEVİZ', 'CEZA',
  'CİLT', 'CİN', 'CUMA', 'CÜMLE', 'DAİRE', 'DAL', 'DALGA', 'DAM',
  'DAMLA', 'DANA', 'DANS', 'DANTEL', 'DARI', 'DAVA', 'DAVUL', 'DAĞ',
  'DEDE', 'DEFNE', 'DEFTER', 'DELİ', 'DELİK', 'DEMİR', 'DEMLİK', 'DENİZ',
  'DERS', 'DESTE', 'DEV', 'DEVLET', 'DEĞİRMEN', 'DİL', 'DİLEK', 'DİLİM',
  'DİP', 'DİREK', 'DİZ', 'DİŞ', 'DOKTOR', 'DOLAP', 'DOLU', 'DOMATES',
  'DOST', 'DOSYA', 'DOĞA', 'DOĞU', 'DUA', 'DUDAK', 'DUMAN', 'DUR',
  'DURAK', 'DUVAR', 'DUYGU', 'DÜDÜK', 'DÜKKAN', 'DÜNYA', 'DÜĞME', 'DÜĞÜN',
  'DÜŞ', 'DÜŞÜNCE', 'DIŞ', 'EBE', 'ECZA', 'EDEBİYAT', 'EFE', 'EFLATUN',
  'EK', 'EKİM', 'EKMEK', 'EKRAN', 'EL', 'ELBİSE', 'ELDİVEN', 'ELEK',
  'ELMA', 'EMEK', 'EMİR', 'ENERJİ', 'ENSE', 'ENSTRÜMAN', 'ERİK', 'ERKEK',
  'ET', 'ETEK', 'ETKİ', 'EV', 'EYLEM', 'EYLÜL', 'EZBER', 'EĞİTİM',
  'EĞRİ', 'FAİZ', 'FAKİR', 'FAL', 'FARE', 'FASULYE', 'FATURA', 'FELSEFE',
  'FENER', 'FİDAN', 'FİKİR', 'FİLE', 'FİLM', 'FİNCAN', 'FİRMA', 'FİS',
  'FİŞEK', 'FORM', 'FOTOĞRAF', 'FUTBOL', 'FIRÇA', 'FIRIN', 'FISTIK', 'FISILTI',
  'FITIK', 'GAGA', 'GALİP', 'GAR', 'GARAJ', 'GAZ', 'GAZETE', 'GECE',
  'GELİN', 'GELİNCİK', 'GEMİ', 'GENÇ', 'GERGİN', 'GERÇEK', 'GEZİ', 'GEÇİT',
  'GİDER', 'GİTAR', 'GİYİM', 'GİZLİ', 'GRAMER', 'GRUP', 'GURBET', 'GÖBEK',
  'GÖL', 'GÖLGE', 'GÖMLEK', 'GÖNÜL', 'GÖREV', 'GÖRÜŞ', 'GÖZ', 'GÖÇ',
  'GÜL', 'GÜLÜŞ', 'GÜMÜŞ', 'GÜN', 'GÜNEŞ', 'GÜVERCİN', 'GÜZ', 'HAFTA',
  'HAKİM', 'HAL', 'HALKA', 'HALI', 'HAMAK', 'HAMAM', 'HAMSİ', 'HANCI',
  'HANGAR', 'HAP', 'HARF', 'HARİTA', 'HASAT', 'HASTANE', 'HASIR', 'HAT',
  'HAVA', 'HAVLU', 'HAVUZ', 'HAVUÇ', 'HAYAT', 'HAYVAN', 'HAZİNE', 'HEDİYE',
  'HELA', 'HEMŞİRE', 'HENDEK', 'HESAP', 'HEVES', 'HEYKEL', 'HİKAYE', 'HİNDİ',
  'HİSSE', 'HOCA', 'HOROZ', 'HUKUK', 'HUZUR', 'HÜCRE', 'HIZ', 'HIÇKIRIK',
  'İKRAM', 'İL', 'İLAN', 'İLAÇ', 'İLGİ', 'İLİM', 'İLKE', 'İLÇE',
  'İMZA', 'İNCİ', 'İNCİR', 'İNEK', 'İNSAN', 'İPEK', 'İPLİK', 'İRADE',
  'İSİM', 'İSTEK', 'İSTİRİDYE', 'İT', 'İZİN', 'İĞNE', 'İŞ', 'İŞARET',
  'JAGUAR', 'JANDARMA', 'JEL', 'JENERATÖR', 'JEST', 'JETON', 'JİLET', 'JİMNASTİK',
  'JOKEY', 'JÖLE', 'KABA', 'KABAK', 'KABUK', 'KADEH', 'KADIN', 'KAFA',
  'KAFES', 'KAHVE', 'KALAS', 'KALE', 'KALEM', 'KALP', 'KAMERA', 'KAMIŞ',
  'KAN', 'KANAL', 'KANAT', 'KANEPE', 'KAPAK', 'KAPLAN', 'KAPI', 'KAR',
  'KARA', 'KARANFİL', 'KARDEŞ', 'KARPUZ', 'KART', 'KARINCA', 'KASA', 'KASAP',
  'KASE', 'KASET', 'KASK', 'KAT', 'KATIR', 'KAVAK', 'KAVUN', 'KAYAK',
  'KAYNAK', 'KAYIK', 'KAYISI', 'KAZ', 'KAZAK', 'KAZAN', 'KAĞIT', 'KAŞIK',
  'KEDİ', 'KEFAL', 'KELEBEK', 'KELİME', 'KEMER', 'KEMİK', 'KENAR', 'KENT',
  'KEPÇE', 'KERESTE', 'KERPETEN', 'KERVAN', 'KESE', 'KESTANE', 'KETEN', 'KİLİM',
  'KİLİT', 'KİLO', 'KİMYA', 'KİRAZ', 'KİTAP', 'KİŞİ', 'KOLA', 'KOLYE',
  'KOMŞU', 'KONAK', 'KONGRE', 'KONSER', 'KONTROL', 'KONU', 'KOPYA', 'KORO',
  'KORUK', 'KOVAN', 'KOYUN', 'KOŞU', 'KRAL', 'KRAVAT', 'KULE', 'KULÜP',
  'KUM', 'KUMAŞ', 'KUMBARA', 'KUPA', 'KURBAĞA', 'KURDELE', 'KURT', 'KURU',
  'KURŞUN', 'KUTU', 'KUYRUK', 'KUYU', 'KUZU', 'KUĞU', 'KUŞ', 'KÖFTE',
  'KÖPEK', 'KÖPRÜ', 'KÖR', 'KÖY', 'KÖŞE', 'KÜFE', 'KÜP', 'KÜREK',
  'KÜRK', 'KÜT', 'KÜÇÜK', 'KILIÇ', 'KIRMIZI', 'KISIM', 'KIŞ', 'LAHANA',
  'LALE', 'LAMBA', 'LASTİK', 'LATİN', 'LAVABO', 'LEKE', 'LEZZET', 'LİMAN',
  'LİMON', 'LİRA', 'LİSE', 'LİSTE', 'LOKANTA', 'LOKMA', 'LOKUM', 'LÜFER',
  'MAAŞ', 'MACERA', 'MADDE', 'MADEN', 'MAHALLE', 'MAKAS', 'MAKİNE', 'MAL',
  'MANAV', 'MANDAL', 'MANTAR', 'MANZARA', 'MARUL', 'MASA', 'MASAL', 'MASKE',
  'MATBAA', 'MAVİ', 'MAYDANOZ', 'MAYIS', 'MAĞARA', 'MEKTUP', 'MELEK', 'MEMUR',
  'MENDİL', 'MENEKŞE', 'MERAK', 'MERDİVEN', 'MERMER', 'MERSİN', 'MEYDAN', 'MEYVE',
  'MEZAR', 'MİDE', 'MİDYE', 'MİMAR', 'MİNDER', 'MİNERAL', 'MİNİK', 'MİSAFİR',
  'MOBİLYA', 'MODA', 'MOLA', 'MOTOR', 'MUHTAR', 'MUM', 'MUSLUK', 'MUTFAK',
  'MUZ', 'MÜDÜR', 'MÜZE', 'MÜZİK', 'MISIR', 'NAKİT', 'NANE', 'NAR',
  'NARİN', 'NEFES', 'NEHİR', 'NEM', 'NESİL', 'NESNE', 'NEŞE', 'NİKAH',
  'NİSAN', 'NİŞAN', 'NOKTA', 'NOT', 'NUMARA', 'NUR', 'NÖBET', 'NÜFUS',
  'OCAK', 'ODA', 'ODUN', 'OFİS', 'OK', 'OKUL', 'OKYANUS', 'OLAY',
  'OLTA', 'OMUZ', 'ON', 'ONUR', 'OPERA', 'ORAK', 'ORAN', 'ORDU',
  'ORMAN', 'ORTA', 'ORUÇ', 'OSURMAK', 'OT', 'OTEL', 'OTOBÜS', 'OTURAK',
  'OYUN', 'OĞLAN', 'PABUÇ', 'PAHALI', 'PAKET', 'PALET', 'PALTO', 'PAMUK',
  'PANJUR', 'PANTOLON', 'PAPATYA', 'PAPAĞAN', 'PARA', 'PARK', 'PARMAK', 'PARÇA',
  'PASTA', 'PASTANE', 'PATATES', 'PATEN', 'PATİKA', 'PATLICAN', 'PAZAR', 'PAZEN',
  'PEHLİVAN', 'PELERİN', 'PENCERE', 'PERDE', 'PERİ', 'PERON', 'PEYNİR', 'PİDE',
  'PİL', 'PİLOT', 'PİRİNÇ', 'PİŞMİŞ', 'PLAJ', 'PLAKA', 'PLAN', 'POLİS',
  'PORSELEN', 'POSTA', 'POTA', 'PROGRAM', 'PROJE', 'PUAN', 'PUL', 'PUSULA',
  'PINAR', 'RADYO', 'RAF', 'RAKAM', 'RAKİP', 'RAMAZAN', 'RAP', 'REHBER',
  'RENK', 'RESİM', 'RİCA', 'RİTİM', 'ROMAN', 'RUH', 'RUTUBET', 'RÖMORK',
  'RÜYA', 'RÜZGAR', 'RIHTIM', 'SAAT', 'SABAH', 'SABUN', 'SADELİK', 'SAHA',
  'SAHİL', 'SAKAL', 'SAKSI', 'SALATA', 'SALEP', 'SALON', 'SALYANGOZ', 'SALÇA',
  'SANAT', 'SANDAL', 'SANDIK', 'SANİYE', 'SANIK', 'SAP', 'SARI', 'SARIMSAK',
  'SATRANÇ', 'SATIR', 'SAVAŞ', 'SAYFA', 'SAYI', 'SAZ', 'SAÇ', 'SAĞLIK',
  'SEANS', 'SEBZE', 'SEDEF', 'SEFER', 'SEHER', 'SEHPA', 'SEL', 'SELAM',
  'SEMA', 'SEMT', 'SENET', 'SEPET', 'SERGİ', 'SERİN', 'SERSEM', 'SERT',
  'SERVİS', 'SERÇE', 'SES', 'SEVGİ', 'SEZON', 'SEÇİM', 'SİMİT', 'SİNEK',
  'SİNEMA', 'SİRKE', 'SİS', 'SİTE', 'SİVRİ', 'SİYAH', 'SOBA', 'SOFRA',
  'SOKAK', 'SOL', 'SOLUCAN', 'SOMUN', 'SON', 'SONUÇ', 'SOPA', 'SORGU',
  'SORU', 'SOSİS', 'SOYAD', 'SOĞAN', 'SPOR', 'SU', 'SUBAY', 'SUCUK',
  'SUNUM', 'SURAT', 'SUSAM', 'SÖZ', 'SÜPÜRGE', 'SÜRE', 'SÜS', 'SÜT',
  'SÜTUN', 'SICAK', 'SIFIR', 'SIRA', 'SIRT', 'SIZI', 'TABAK', 'TABLO',
  'TAHTA', 'TAKVİM', 'TAKIM', 'TALAŞ', 'TALEBE', 'TANE', 'TARAK', 'TARİH',
  'TARLA', 'TARÇIN', 'TAT', 'TATİL', 'TAVA', 'TAVAN', 'TAVLA', 'TAVUK',
  'TAVŞAN', 'TAZE', 'TAZI', 'TAŞ', 'TAŞIT', 'TEBEŞİR', 'TEKNE', 'TEL',
  'TELEFON', 'TELEVİZYON', 'TEMEL', 'TEMİZ', 'TENCERE', 'TENİS', 'TEPE', 'TEPSİ',
  'TERAZİ', 'TERCİH', 'TERLİK', 'TERS', 'TERSANE', 'TEYZE', 'TİCARET', 'TİLKİ',
  'TİYATRO', 'TOKA', 'TOKAT', 'TOP', 'TOPLUM', 'TOPRAK', 'TORBA', 'TORUN',
  'TOST', 'TREN', 'TUZ', 'TUZAK', 'TUĞLA', 'TUŞE', 'TÜFEK', 'TÜNEL',
  'TÜP', 'TÜRKÜ', 'TÜTÜN', 'TIRNAK', 'UFUK', 'ULUS', 'UMUT', 'UN',
  'UNVAN', 'USTA', 'USUL', 'UYKU', 'UZAY', 'UZMAN', 'UÇAK', 'UÇURTMA',
  'UĞUR', 'VADİ', 'VAGON', 'VAKİT', 'VALİZ', 'VANİLYA', 'VAPUR', 'VARLIK',
  'VAZO', 'VERGİ', 'VERİ', 'VİNÇ', 'VİRAJ', 'VİTRİN', 'VİŞNE', 'VÜCUT',
  'YABAN', 'YAKA', 'YAPRAK', 'YARA', 'YARIŞ', 'YASA', 'YASTIK', 'YATAK',
  'YAVRU', 'YAY', 'YAYLA', 'YAZ', 'YAZAR', 'YAZI', 'YAĞMUR', 'YELEK',
  'YELKEN', 'YEMEK', 'YEMİŞ', 'YENGE', 'YENİ', 'YER', 'YEŞİL', 'YİĞİT',
  'YOL', 'YOLCU', 'YORGAN', 'YOSUN', 'YULAF', 'YUMRUK', 'YUMURTA', 'YURT',
  'YUVA', 'YÖN', 'YÜZ', 'YÜZÜK', 'YIL', 'YILDIZ', 'ZAFER', 'ZAMAN',
  'ZAMBAK', 'ZARF', 'ZEYTİN', 'ZİL', 'ZİNCİR', 'ZİNDAN', 'ZURNA', 'ZÜMRÜT',
  'ÇADIR', 'ÇAKMAK', 'ÇAKIL', 'ÇAM', 'ÇAMUR', 'ÇANAK', 'ÇANTA', 'ÇARE',
  'ÇARŞAF', 'ÇARŞI', 'ÇATAL', 'ÇATI', 'ÇAY', 'ÇAYIR', 'ÇEKİÇ', 'ÇELİK',
  'ÇEMBER', 'ÇENE', 'ÇENGEL', 'ÇEYREK', 'ÇEŞME', 'ÇİFT', 'ÇİLEK', 'ÇİMEN',
  'ÇİZGİ', 'ÇİÇEK', 'ÇOBAN', 'ÇOCUK', 'ÇORAP', 'ÇORBA', 'ÇUVAL', 'ÇÜRÜK',
  'ÇIKIŞ', 'ÇIĞLIK', 'ÖKSÜRÜK', 'ÖKÇE', 'ÖLÇÜ', 'ÖMÜR', 'ÖRDEK', 'ÖRGÜ',
  'ÖRNEK', 'ÖRTÜ', 'ÖYKÜ', 'ÖZ', 'ÖZEL', 'ÖZGÜR', 'ÖĞLE', 'ÖĞRENCİ',
  'ÖĞRETMEN', 'ÖĞÜT', 'ÜCRET', 'ÜLKE', 'ÜMİT', 'ÜN', 'ÜNİVERSİTE', 'ÜRÜN',
  'ÜSTAT', 'ÜZÜM', 'ÜÇGEN', 'ISLIK', 'ISI', 'IZGARA', 'IŞIK', 'ŞAİR',
  'ŞAKA', 'ŞALGAM', 'ŞAPKA', 'ŞARAP', 'ŞARKI', 'ŞART', 'ŞEFTALİ', 'ŞEKER',
  'ŞEKİL', 'ŞEMSİYE', 'ŞERBET', 'ŞEREF', 'ŞEY', 'ŞİİR', 'ŞİMŞEK', 'ŞİRKET',
  'ŞİŞE', 'ŞOFÖR', 'ŞURUP',
]);
